export PYENV_ROOT="${HOME}/.pyenv"
export GOPATH="${HOME}/go"
export PATH="${GOPATH}/bin:${PYENV_ROOT}/bin:/snap/bin:${PATH}"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

export PYTHON_CONFIGURE_OPTS="--enable-shared"
export PIPENV_VENV_IN_PROJECT=1

